# Generated by Django 5.2.17 on 2026-09-29 11:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceCampaignDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "objective",
                    models.CharField(
                        choices=[("lead_generation", "Lead generation")],
                        default="lead_generation",
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("google_search", "Google Search")],
                        default="google_search",
                        max_length=32,
                    ),
                ),
                ("brief", models.TextField(max_length=4000)),
                ("target_city", models.CharField(max_length=100)),
                ("destination_url", models.URLField(blank=True, max_length=500)),
                (
                    "media_budget_minor",
                    models.PositiveBigIntegerField(
                        help_text="Integer minor units; independent of GrowthTwin fees and credits.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("currency", models.CharField(default="TRY", max_length=3)),
                ("flight_start", models.DateField(blank=True, null=True)),
                ("flight_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_drafts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "pk"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("media_budget_minor__gt", 0)),
                        name="campaign_draft_positive_media_budget",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("flight_start__isnull", True),
                            ("flight_end__isnull", True),
                            ("flight_end__gte", models.F("flight_start")),
                            _connector="OR",
                        ),
                        name="campaign_draft_flight_dates_ordered",
                    ),
                ],
            },
        ),
    ]
