# Generated by Django 5.2.17 on 2026-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecampaigndraft",
            name="brand_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
