# Generated by Django 5.2.17 on 2026-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_workspacecampaigndraft_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacecampaigndraft",
            name="creative_versions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
