# Generated by Django 5.2.17 on 2026-09-27 23:20

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brief", models.CharField(max_length=280)),
                ("daily_limit", models.PositiveIntegerField()),
                ("duration_days", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Taslak")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_drafts",
                        to="sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(daily_limit__gte=100) & Q(daily_limit__lte=100000),
                        name="campaign_draft_daily_limit_range",
                    ),
                    models.CheckConstraint(
                        condition=Q(duration_days__in=(7, 14, 30)),
                        name="campaign_draft_duration_allowed",
                    ),
                ],
            },
        ),
    ]
