# Generated by Django 5.2.17 on 2026-09-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("site", "0002_campaigndraft_brand_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndraft",
            name="objective",
            field=models.CharField(
                blank=True,
                choices=[
                    ("awareness", "Markamı daha çok kişiye duyurmak"),
                    ("traffic", "Web siteme ziyaretçi çekmek"),
                    ("leads", "Potansiyel müşteri bulmak"),
                    ("sales", "Satış, randevu veya rezervasyon almak"),
                    ("local_visits", "Mağaza veya konum ziyareti sağlamak"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="campaigndraft",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("objective", ""),
                    (
                        "objective__in",
                        ["awareness", "traffic", "leads", "sales", "local_visits"],
                    ),
                    _connector="OR",
                ),
                name="campaign_draft_objective_allowed",
            ),
        ),
    ]
