# Generated by Django 5.2.17 on 2026-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0003_campaigndraft_objective_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigndraft",
            name="target_audience",
            field=models.CharField(blank=True, default="", max_length=240),
        ),
    ]
